### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by tyeeman** [lanqy/mksite.go#2]
This looks real nice. I tried to build on Windows and got this error -

```
mksite.go:20:2: cannot find package "github.com/daryl/fmatter" in any of:
        C:\go\src\github.com\daryl\fmatter (from $GOROOT)
        C:\goWorkspace\src\github.com\daryl\fmatter (from $GOPATH)
mksite.go:21:2: cannot find package "github.com/mgutz/ansi" in any of:
        C:\go\src\github.com\mgutz\ansi (from $GOROOT)
        C:\goWorkspace\src\github.com\mgutz\ansi (from $GOPATH)
```
I tried go get github.com/lanqy/mksite.go and got this error - 

```
c:\goWorkspace>go get github.com/lanqy/mksite.go
CreateFile github.com/lanqy/mksite.go: The system cannot find the path specified.
```
Update - I managed to get it to run in mksite folder so it's working now but I believe I did need to use the command ``` go get ``` first.

Only thing I see this needs is tags, is it easy to add them? 

Update 2 - Looks like it's running ok except for navs--

![2019-02-22_220806](https://user-images.githubusercontent.com/4469306/53282593-c236d300-36ee-11e9-8e79-c1424a0e8d48.png)

**Comment by lanqy** [comment]
@tyeeman Sorry, I missed the homepage and it is now fixed. Adding tags should not be difficult, I will try to implement it.

**Comment by tyeeman** [comment]
Thanks, I will try it again. Just a quick mention - I think I had problems above installing because of that dot in the name mksite.go. It may be just a Windows problem but I do remember another error about Windows looking for a file instead of a folder or vice versa. If there is a dot Windows thinks it's a file but in this case it was a folder so it got confused. Maybe it should be called mksite_go instead just to remove the dot. Just a suggestion. Ok, I just ran the new version and the nav is working. The error above prevents the exe from being built when using ```go get```, but I ran the exe build command from the mksite.go folder directly and it works, but it would be better to change the name to remove the dot.

**Comment by lanqy** [comment]
@tyeeman Thank you for you suggestion, mksite_go doesn't look very elegant, mksite should be the best, but I already have another Node.js project (https://github.com/lanqy/mksite). So is  it's not renamed yet. I will indicate in the readme file that windows cannot use ```go get``` command, BTW, I add tags support now , you can have a try :)

**Comment by tyeeman** [comment]
Ok, I'll try tags. 
Update - Tags show but are not clickable. It would be nice to be able to click any tag on a post page then be taken to a new page that shows all posts that have that tag and be able to click on any of those posts. Is this easy to do?

**Comment by lanqy** [comment]
@tyeeman If you want the tag clickable and shows all posts contain this tag, This is more complicated to implement，Maybe you can use other alternatives, such as dynamic blogging systems like Wordpress.

**Comment by tyeeman** [comment]
OK, thanks for thinking about it.
